import React from 'react';
import BreadCrumb from '../components/BreadCrumb';
import MetaData from '../utils/MetaData';

const TermsAndCondition = () => {
  return (
    <>
      <MetaData title='Terms and Conditions' />
      <BreadCrumb title='Terms and Conditions' />

      <div className='policy-wrapper p-4 home-wrapper-2'>
        <div className='container-xxl'>
          <div className='row'>
            <div className='col-12'>
              <div className='policy'>
                <code className='text-dark'>June 3rd ,2022</code>
                <h3 className='title text-center'>TERMS OF USE</h3>
                <div>
                  <p>
                    This document is an electronic record in terms of
                    Information Technology Act, 2000 and rules there under as
                    applicable and the amended provisions pertaining to
                    electronic records in various statutes as amended by the
                    Information Technology Act, 2000. This electronic record is
                    generated by a computer system and does not require any
                    physical or digital signatures.
                  </p>
                  <p>
                    This document is published in accordance with the provisions
                    of Rule 3 (1) of the Information Technology (Intermediaries
                    guidelines) Rules, 2011 that require publishing the rules
                    and regulations, privacy policy and Terms of Use for access
                    or usage of domain name [www.shopnow.com][www.shopnow.com]
                    (“Website”), including the related mobile site and mobile
                    application (hereinafter referred to as “Platform”)
                  </p>
                  <p>
                    For the purpose of these Terms of Use, wherever the context
                    so requires "You" or "User" shall mean any natural or legal
                    person who has agreed to become a buyer on the Platform by
                    providing Registration Data while registering on the
                    Platform as Registered User using the computer systems.
                    Shop-Now allows the User to surf the Platform or making
                    purchases without registering on the Platform. The term
                    "We", "Us", "Our" shall mean Shop-Now Internet Private
                    Limited.
                  </p>

                  <h6>
                    Why does the delivery date not correspond to the delivery
                    timeline of X-Y business days?
                  </h6>

                  <p>
                    When You use any of the services provided by Us through the
                    Platform, including but not limited to, (e.g. Product
                    Reviews, Seller Reviews), You will be subject to the rules,
                    guidelines, policies, terms, and conditions applicable to
                    such service, and they shall be deemed to be incorporated
                    into this Terms of Use and shall be considered as part and
                    parcel of this Terms of Use. We reserve the right, at Our
                    sole discretion, to change, modify, add or remove portions
                    of these Terms of Use, at any time without any prior written
                    notice to You. It is Your responsibility to review these
                    Terms of Use periodically for updates / changes. Your
                    continued use of the Platform following the posting of
                    changes will mean that You accept and agree to the
                    revisions. As long as You comply with these Terms of Use, We
                    grant You a personal, non-exclusive, non-transferable,
                    limited privilege to enter and use the Platform.
                  </p>

                  <p>
                    Sellers generally procure and ship the items within the time
                    specified on the product page. Business days exclude public
                    holidays and Sundays.
                  </p>

                  <p>
                    Transaction on the Platform is available only to persons who
                    can form legally binding contracts under Indian Contract
                    Act, 1872. Persons who are "incompetent to contract" within
                    the meaning of the Indian Contract Act, 1872 including
                    un-discharged insolvents etc. are not eligible to use the
                    Platform. If you are a minor i.e. under the age of 18 years,
                    you may use the Platform or access content on the Platform
                    only under the supervision and prior consent/ permission of
                    a parent ormlegal guardian.
                  </p>

                  <p>
                    If You use the Platform, You shall be responsible for
                    maintaining the confidentiality of your Display Name and
                    Password and You shall be responsible for all activities
                    that occur under your Display Name and Password. You agree
                    that if You provide any information that is untrue,
                    inaccurate, not current or incomplete or We have reasonable
                    grounds to suspect that such information is untrue,
                    inaccurate, not current or incomplete, or not in accordance
                    with the this Terms of Use, We shall have the right to
                    indefinitely suspend or terminate or block access of your
                    membership on the Platform and refuse to provide You with
                    access to the Platform.
                  </p>

                  <p>
                    Your mobile phone number and/or e-mail address is treated as
                    Your primary identifier on the Platform. It is your
                    responsibility to ensure that Your mobile phone number and
                    your email address is up to date on the Platform at all
                    times. You agree to notify Us promptly if your mobile phone
                    number or e-mail address changes by updating the same on the
                    Platform through a onetime password verification.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default TermsAndCondition;
