export const ALL_BLOGS_REQUEST = 'ALL_BLOGS_REQUEST';
export const ALL_BLOGS_SUCCESS = 'ALL_BLOGS_SUCCESS';
export const ALL_BLOGS_FAIL = 'ALL_BLOGS_FAIL';

export const SINGLE_BLOG_REQUEST = 'SINGLE_BLOG_REQUEST';
export const SINGLE_BLOG_SUCCESS = 'SINGLE_BLOG_SUCCESS';
export const SINGLE_BLOG_FAIL = 'SINGLE_BLOG_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
