export const ALL_BLOGS_CATEGORY_REQUEST = 'ALL_BLOGS_CATEGORY_REQUEST';
export const ALL_BLOGS_CATEGORY_SUCCESS = 'ALL_BLOGS_CATEGORY_SUCCESS';
export const ALL_BLOGS_CATEGORY_FAIL = 'ALL_BLOGS_CATEGORY_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
