export const ALL_BLOGS_REQUEST = 'ALL_BLOGS_REQUEST';
export const ALL_BLOGS_SUCCESS = 'ALL_BLOGS_SUCCESS';
export const ALL_BLOGS_FAIL = 'ALL_BLOGS_FAIL';

export const SINGLE_BLOG_REQUEST = 'SINGLE_BLOG_REQUEST';
export const SINGLE_BLOG_SUCCESS = 'SINGLE_BLOG_SUCCESS';
export const SINGLE_BLOG_FAIL = 'SINGLE_BLOG_FAIL';

export const LIKE_BLOG_REQUEST = 'LIKE_BLOG_REQUEST';
export const LIKE_BLOG_SUCCESS = 'LIKE_BLOG_SUCCESS';
export const LIKE_BLOG_FAIL = 'LIKE_BLOG_FAIL';
export const LIKE_BLOG_RESET = 'LIKE_BLOG_RESET';

export const DISLIKE_BLOG_REQUEST = 'DISLIKE_BLOG_REQUEST';
export const DISLIKE_BLOG_SUCCESS = 'DISLIKE_BLOG_SUCCESS';
export const DISLIKE_BLOG_FAIL = 'DISLIKE_BLOG_FAIL';
export const DISLIKE_BLOG_RESET = 'DISLIKE_BLOG_RESET';

export const DELETE_BLOG_REQUEST = 'DELETE_BLOG_REQUEST';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAIL = 'DELETE_BLOG_FAIL';
export const DELETE_BLOG_RESET = 'DELETE_BLOG_RESET';

export const CREATE_BLOG_REQUEST = 'CREATE_BLOG_REQUEST';
export const CREATE_BLOG_SUCCESS = 'CREATE_BLOG_SUCCESS';
export const CREATE_BLOG_FAIL = 'CREATE_BLOG_FAIL';
export const CREATE_BLOG_RESET = 'CREATE_BLOG_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
