export const ALL_BLOGS_CATEGORY_REQUEST = 'ALL_BLOGS_CATEGORY_REQUEST';
export const ALL_BLOGS_CATEGORY_SUCCESS = 'ALL_BLOGS_CATEGORY_SUCCESS';
export const ALL_BLOGS_CATEGORY_FAIL = 'ALL_BLOGS_CATEGORY_FAIL';

export const BLOGS_CATEGORY_DETAILS_REQUEST = 'BLOGS_CATEGORY_DETAILS_REQUEST';
export const BLOGS_CATEGORY_DETAILS_SUCCESS = 'BLOGS_CATEGORY_DETAILS_SUCCESS';
export const BLOGS_CATEGORY_DETAILS_FAIL = 'BLOGS_CATEGORY_DETAILS_FAIL';

export const DELETE_BLOG_CATEGORY_REQUEST = 'DELETE_BLOG_CATEGORY_REQUEST';
export const DELETE_BLOG_CATEGORY_SUCCESS = 'DELETE_BLOG_CATEGORY_SUCCESS';
export const DELETE_BLOG_CATEGORY_FAIL = 'DELETE_BLOG_CATEGORY_FAIL';
export const DELETE_BLOG_CATEGORY_RESET = 'DELETE_BLOG_CATEGORY_RESET';

export const CREATE_BLOG_CATEGORY_REQUEST = 'CREATE_BLOG_CATEGORY_REQUEST';
export const CREATE_BLOG_CATEGORY_SUCCESS = 'CREATE_BLOG_CATEGORY_SUCCESS';
export const CREATE_BLOG_CATEGORY_FAIL = 'CREATE_BLOG_CATEGORY_FAIL';
export const CREATE_BLOG_CATEGORY_RESET = 'CREATE_BLOG_CATEGORY_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
