export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';
export const ADD_TO_CART_RESET = 'ADD_TO_CART_RESET';

export const REMOVE_CART_ITEM_REQUEST = 'REMOVE_CART_ITEM_REQUEST';
export const REMOVE_CART_ITEM_SUCCESS = 'REMOVE_CART_ITEM_SUCCESS';
export const REMOVE_CART_ITEM_FAIL = 'REMOVE_CART_ITEM_FAIL';
export const REMOVE_CART_ITEM_RESET = 'REMOVE_CART_ITEM_RESET';

export const USER_CART_REQUEST = 'USER_CART_REQUEST';
export const USER_CART_SUCCESS = 'USER_CART_SUCCESS';
export const USER_CART_FAIL = 'USER_CART_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
