export const ALL_COUPON_REQUEST = 'ALL_COUPON_REQUEST';
export const ALL_COUPON_SUCCESS = 'ALL_COUPON_SUCCESS';
export const ALL_COUPON_FAIL = 'ALL_COUPON_FAIL';

export const COUPON_DETAILS_REQUEST = 'COUPON_DETAILS_REQUEST';
export const COUPON_DETAILS_SUCCESS = 'COUPON_DETAILS_SUCCESS';
export const COUPON_DETAILS_FAIL = 'COUPON_DETAILS_FAIL';

export const APPLY_COUPON_REQUEST = 'APPLY_COUPON_REQUEST';
export const APPLY_COUPON_SUCCESS = 'APPLY_COUPON_SUCCESS';
export const APPLY_COUPON_FAIL = 'APPLY_COUPON_FAIL';
export const APPLY_COUPON_RESET = 'APPLY_COUPON_RESET';

export const DELETE_COUPON_REQUEST = 'DELETE_COUPON_REQUEST';
export const DELETE_COUPON_SUCCESS = 'DELETE_COUPON_SUCCESS';
export const DELETE_COUPON_FAIL = 'DELETE_COUPON_FAIL';
export const DELETE_COUPON_RESET = 'DELETE_COUPON_RESET';

export const CREATE_COUPON_REQUEST = 'CREATE_COUPON_REQUEST';
export const CREATE_COUPON_SUCCESS = 'CREATE_COUPON_SUCCESS';
export const CREATE_COUPON_FAIL = 'CREATE_COUPON_FAIL';
export const CREATE_COUPON_RESET = 'CREATE_COUPON_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
