export const ALL_FAQ_CATEGORY_REQUEST = 'ALL_FAQ_CATEGORY_REQUEST';
export const ALL_FAQ_CATEGORY_SUCCESS = 'ALL_FAQ_CATEGORY_SUCCESS';
export const ALL_FAQ_CATEGORY_FAIL = 'ALL_FAQ_CATEGORY_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
