export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';
export const CREATE_ORDER_RESET = 'CREATE_ORDER_RESET';

export const ALL_ORDERS_REQUEST = 'ALL_ORDERS_REQUEST';
export const ALL_ORDERS_SUCCESS = 'ALL_ORDERS_SUCCESS';
export const ALL_ORDERS_FAIL = 'ALL_ORDERS_FAIL';

export const PENDING_ORDERS_REQUEST = 'PENDING_ORDERS_REQUEST';
export const PENDING_ORDERS_SUCCESS = 'PENDING_ORDERS_SUCCESS';
export const PENDING_ORDERS_FAIL = 'PENDING_ORDERS_FAIL';

export const SHIPPED_ORDERS_REQUEST = 'SHIPPED_ORDERS_REQUEST';
export const SHIPPED_ORDERS_SUCCESS = 'SHIPPED_ORDERS_SUCCESS';
export const SHIPPED_ORDERS_FAIL = 'SHIPPED_ORDERS_FAIL';

export const OUT_FOR_DELIVERY_REQUEST = 'OUT_FOR_DELIVERY_REQUEST';
export const OUT_FOR_DELIVERY_SUCCESS = 'OUT_FOR_DELIVERY_SUCCESS';
export const OUT_FOR_DELIVERY_FAIL = 'OUT_FOR_DELIVERY_FAIL';

export const DELIVERED_ORDERS_REQUEST = 'DELIVERED_ORDERS_REQUEST';
export const DELIVERED_ORDERS_SUCCESS = 'DELIVERED_ORDERS_SUCCESS';
export const DELIVERED_ORDERS_FAIL = 'DELIVERED_ORDERS_FAIL';

export const ALL_ORDERS_ADMIN_REQUEST = 'ALL_ORDERS_ADMIN_REQUEST';
export const ALL_ORDERS_ADMIN_SUCCESS = 'ALL_ORDERS_ADMIN_SUCCESS';
export const ALL_ORDERS_ADMIN_FAIL = 'ALL_ORDERS_ADMIN_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_DETAILS_ADMIN_REQUEST = 'ORDER_DETAILS_ADMIN_REQUEST';
export const ORDER_DETAILS_ADMIN_SUCCESS = 'ORDER_DETAILS_ADMIN_SUCCESS';
export const ORDER_DETAILS_ADMIN_FAIL = 'ORDER_DETAILS_ADMIN_FAIL';

export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAIL = 'UPDATE_ORDER_STATUS_FAIL';
export const UPDATE_ORDER_STATUS_RESET = 'CREATE_ORDER_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
