export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';
export const CREATE_ORDER_RESET = 'CREATE_ORDER_RESET';

export const ALL_ORDERS_REQUEST = 'ALL_ORDERS_REQUEST';
export const ALL_ORDERS_SUCCESS = 'ALL_ORDERS_SUCCESS';
export const ALL_ORDERS_FAIL = 'ALL_ORDERS_FAIL';

export const ALL_ORDERS_ADMIN_REQUEST = 'ALL_ORDERS_ADMIN_REQUEST';
export const ALL_ORDERS_ADMIN_SUCCESS = 'ALL_ORDERS_ADMIN_SUCCESS';
export const ALL_ORDERS_ADMIN_FAIL = 'ALL_ORDERS_ADMIN_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_DETAILS_ADMIN_REQUEST = 'ORDER_DETAILS_ADMIN_REQUEST';
export const ORDER_DETAILS_ADMIN_SUCCESS = 'ORDER_DETAILS_ADMIN_SUCCESS';
export const ORDER_DETAILS_ADMIN_FAIL = 'ORDER_DETAILS_ADMIN_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
