export const ALL_BRAND_REQUEST = 'ALL_BRAND_REQUEST';
export const ALL_BRAND_SUCCESS = 'ALL_BRAND_SUCCESS';
export const ALL_BRAND_FAIL = 'ALL_BRAND_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
