export const ALL_PRODUCTCATEGORY_REQUEST = 'ALL_PRODUCTCATEGORY_REQUEST';
export const ALL_PRODUCTCATEGORY_SUCCESS = 'ALL_PRODUCTCATEGORY_SUCCESS';
export const ALL_PRODUCTCATEGORY_FAIL = 'ALL_PRODUCTCATEGORY_FAIL';

export const ALL_PRODUCTCATEGORY_COUNT_REQUEST =
  'ALL_PRODUCTCATEGORY_COUNT_REQUEST';
export const ALL_PRODUCTCATEGORY_COUNT_SUCCESS =
  'ALL_PRODUCTCATEGORY_COUNT_SUCCESS';
export const ALL_PRODUCTCATEGORY_COUNT_FAIL = 'ALL_PRODUCTCATEGORY_COUNT_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
