export const ALL_BRAND_REQUEST = 'ALL_BRAND_REQUEST';
export const ALL_BRAND_SUCCESS = 'ALL_BRAND_SUCCESS';
export const ALL_BRAND_FAIL = 'ALL_BRAND_FAIL';

export const DELETE_BRAND_REQUEST = 'DELETE_BRAND_REQUEST';
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS';
export const DELETE_BRAND_FAIL = 'DELETE_BRAND_FAIL';
export const DELETE_BRAND_RESET = 'DELETE_BRAND_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
