export const ALL_COLOR_REQUEST = 'ALL_COLOR_REQUEST';
export const ALL_COLOR_SUCCESS = 'ALL_COLOR_SUCCESS';
export const ALL_COLOR_FAIL = 'ALL_COLOR_FAIL';

export const SINGLE_COLOR_REQUEST = 'SINGLE_COLOR_REQUEST';
export const SINGLE_COLOR_SUCCESS = 'SINGLE_COLOR_SUCCESS';
export const SINGLE_COLOR_FAIL = 'SINGLE_COLOR_FAIL';

export const DELETE_COLOR_REQUEST = 'DELETE_COLOR_REQUEST';
export const DELETE_COLOR_SUCCESS = 'DELETE_COLOR_SUCCESS';
export const DELETE_COLOR_FAIL = 'DELETE_COLOR_FAIL';
export const DELETE_COLOR_RESET = 'DELETE_COLOR_RESET';

export const CREATE_COLOR_REQUEST = 'CREATE_COLOR_REQUEST';
export const CREATE_COLOR_SUCCESS = 'CREATE_COLOR_SUCCESS';
export const CREATE_COLOR_FAIL = 'CREATE_COLOR_FAIL';
export const CREATE_COLOR_RESET = 'CREATE_COLOR_RESET';

export const UPDATE_COLOR_REQUEST = 'UPDATE_COLOR_REQUEST';
export const UPDATE_COLOR_SUCCESS = 'UPDATE_COLOR_SUCCESS';
export const UPDATE_COLOR_FAIL = 'UPDATE_COLOR_FAIL';
export const UPDATE_COLOR_RESET = 'UPDATE_COLOR_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
