export const ALL_PRODUCTCATEGORY_REQUEST = 'ALL_PRODUCTCATEGORY_REQUEST';
export const ALL_PRODUCTCATEGORY_SUCCESS = 'ALL_PRODUCTCATEGORY_SUCCESS';
export const ALL_PRODUCTCATEGORY_FAIL = 'ALL_PRODUCTCATEGORY_FAIL';

export const ALL_PRODUCTCATEGORY_COUNT_REQUEST =
  'ALL_PRODUCTCATEGORY_COUNT_REQUEST';
export const ALL_PRODUCTCATEGORY_COUNT_SUCCESS =
  'ALL_PRODUCTCATEGORY_COUNT_SUCCESS';
export const ALL_PRODUCTCATEGORY_COUNT_FAIL = 'ALL_PRODUCTCATEGORY_COUNT_FAIL';

export const QUICK_CATEGORY_REQUEST = 'QUICK_CATEGORY_REQUEST';
export const QUICK_CATEGORY_SUCCESS = 'QUICK_CATEGORY_SUCCESS';
export const QUICK_CATEGORY_FAIL = 'QUICK_CATEGORY_FAIL';

export const DELETE_PRODUCT_CATEGORY_REQUEST =
  'DELETE_PRODUCT_CATEGORY_REQUEST';
export const DELETE_PRODUCT_CATEGORY_SUCCESS =
  'DELETE_PRODUCT_CATEGORY_SUCCESS';
export const DELETE_PRODUCT_CATEGORY_FAIL = 'DELETE_PRODUCT_CATEGORY_FAIL';
export const DELETE_PRODUCT_CATEGORY_RESET = 'DELETE_PRODUCT_CATEGORY_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
