export const ALL_PRODUCT_REQUEST = 'ALL_PRODUCT_REQUEST';
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS';
export const ALL_PRODUCT_FAIL = 'ALL_PRODUCT_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const RELATED_PRODUCT_REQUEST = 'RELATED_PRODUCT_REQUEST';
export const RELATED_PRODUCT_SUCCESS = 'RELATED_PRODUCT_SUCCESS';
export const RELATED_PRODUCT_FAIL = 'RELATED_PRODUCT_FAIL';

export const RANDOM_PRODUCT_REQUEST = 'RANDOM_PRODUCT_REQUEST';
export const RANDOM_PRODUCT_SUCCESS = 'RANDOM_PRODUCT_SUCCESS';
export const RANDOM_PRODUCT_FAIL = 'RANDOM_PRODUCT_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
