export const ALL_TYPE_REQUEST = 'ALL_TYPE_REQUEST';
export const ALL_TYPE_SUCCESS = 'ALL_TYPE_SUCCESS';
export const ALL_TYPE_FAIL = 'ALL_TYPE_FAIL';

export const ALL_TYPE_COUNT_REQUEST = 'ALL_TYPE_COUNT_REQUEST';
export const ALL_TYPE_COUNT_SUCCESS = 'ALL_TYPE_COUNT_SUCCESS';
export const ALL_TYPE_COUNT_FAIL = 'ALL_TYPE_FAIL';

export const DELETE_TYPE_REQUEST = 'DELETE_TYPE_REQUEST';
export const DELETE_TYPE_SUCCESS = 'DELETE_TYPE_SUCCESS';
export const DELETE_TYPE_FAIL = 'DELETE_TYPE_FAIL';
export const DELETE_TYPE_RESET = 'DELETE_TYPE_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
