export const ALL_PRODUCT_REQUEST = 'ALL_PRODUCT_REQUEST';
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS';
export const ALL_PRODUCT_FAIL = 'ALL_PRODUCT_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const RELATED_PRODUCT_REQUEST = 'RELATED_PRODUCT_REQUEST';
export const RELATED_PRODUCT_SUCCESS = 'RELATED_PRODUCT_SUCCESS';
export const RELATED_PRODUCT_FAIL = 'RELATED_PRODUCT_FAIL';

export const RATING_PRODUCT_REQUEST = 'RATING_PRODUCT_REQUEST';
export const RATING_PRODUCT_SUCCESS = 'RATING_PRODUCT_SUCCESS';
export const RATING_PRODUCT_FAIL = 'RATING_PRODUCT_FAIL';
export const RATING_PRODUCT_RESET = 'RATING_PRODUCT_RESET';

export const RANDOM_PRODUCT_REQUEST = 'RANDOM_PRODUCT_REQUEST';
export const RANDOM_PRODUCT_SUCCESS = 'RANDOM_PRODUCT_SUCCESS';
export const RANDOM_PRODUCT_FAIL = 'RANDOM_PRODUCT_FAIL';

export const POPULAR_PRODUCT_REQUEST = 'POPULAR_PRODUCT_REQUEST';
export const POPULAR_PRODUCT_SUCCESS = 'POPULAR_PRODUCT_SUCCESS';
export const POPULAR_PRODUCT_FAIL = 'POPULAR_PRODUCT_FAIL';

export const FEATURED_PRODUCT_REQUEST = 'FEATURED_PRODUCT_REQUEST';
export const FEATURED_PRODUCT_SUCCESS = 'FEATURED_PRODUCT_SUCCESS';
export const FEATURED_PRODUCT_FAIL = 'FEATURED_PRODUCT_FAIL';

export const SPECIAL_PRODUCT_REQUEST = 'SPECIAL_PRODUCT_REQUEST';
export const SPECIAL_PRODUCT_SUCCESS = 'SPECIAL_PRODUCT_SUCCESS';
export const SPECIAL_PRODUCT_FAIL = 'SPECIAL_PRODUCT_FAIL';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';
export const UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCT_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
