export const ALL_COLOR_REQUEST = 'ALL_COLOR_REQUEST';
export const ALL_COLOR_SUCCESS = 'ALL_COLOR_SUCCESS';
export const ALL_COLOR_FAIL = 'ALL_COLOR_FAIL';

export const DELETE_COLOR_REQUEST = 'DELETE_COLOR_REQUEST';
export const DELETE_COLOR_SUCCESS = 'DELETE_COLOR_SUCCESS';
export const DELETE_COLOR_FAIL = 'DELETE_COLOR_FAIL';
export const DELETE_COLOR_RESET = 'DELETE_COLOR_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
