export const ALL_TYPE_REQUEST = 'ALL_TYPE_REQUEST';
export const ALL_TYPE_SUCCESS = 'ALL_TYPE_SUCCESS';
export const ALL_TYPE_FAIL = 'ALL_TYPE_FAIL';

export const SINGLE_TYPE_REQUEST = 'SINGLE_TYPE_REQUEST';
export const SINGLE_TYPE_SUCCESS = 'SINGLE_TYPE_SUCCESS';
export const SINGLE_TYPE_FAIL = 'SINGLE_TYPE_FAIL';

export const ALL_TYPE_COUNT_REQUEST = 'ALL_TYPE_COUNT_REQUEST';
export const ALL_TYPE_COUNT_SUCCESS = 'ALL_TYPE_COUNT_SUCCESS';
export const ALL_TYPE_COUNT_FAIL = 'ALL_TYPE_FAIL';

export const DELETE_TYPE_REQUEST = 'DELETE_TYPE_REQUEST';
export const DELETE_TYPE_SUCCESS = 'DELETE_TYPE_SUCCESS';
export const DELETE_TYPE_FAIL = 'DELETE_TYPE_FAIL';
export const DELETE_TYPE_RESET = 'DELETE_TYPE_RESET';

export const CREATE_TYPE_REQUEST = 'CREATE_TYPE_REQUEST';
export const CREATE_TYPE_SUCCESS = 'CREATE_TYPE_SUCCESS';
export const CREATE_TYPE_FAIL = 'CREATE_TYPE_FAIL';
export const CREATE_TYPE_RESET = 'CREATE_TYPE_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
