export const ALL_SIZES_REQUEST = 'ALL_SIZES_REQUEST';
export const ALL_SIZES_SUCCESS = 'ALL_SIZES_SUCCESS';
export const ALL_SIZES_FAIL = 'ALL_SIZES_FAIL';

export const DELETE_SIZE_REQUEST = 'DELETE_SIZE_REQUEST';
export const DELETE_SIZE_SUCCESS = 'DELETE_SIZE_SUCCESS';
export const DELETE_SIZE_FAIL = 'DELETE_SIZE_FAIL';
export const DELETE_SIZE_RESET = 'DELETE_SIZE_RESET';

export const CREATE_SIZE_REQUEST = 'CREATE_SIZE_REQUEST';
export const CREATE_SIZE_SUCCESS = 'CREATE_SIZE_SUCCESS';
export const CREATE_SIZE_FAIL = 'CREATE_SIZE_FAIL';
export const CREATE_SIZE_RESET = 'CREATE_SIZE_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
